#apiVersion: v1
#kind: Namespace
#metadata:
#name: stub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stub-deployment
  #namespace: stub
  labels:
    app: stub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stub
  template:
    metadata:
      labels:
        app: stub
  containers:
    - name: hoverfly
      image: spectolabs/hoverfly:latest
      ports:
        - containerPort: 8555
          name: admin
        - containerPort: 8880
          name: access
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - stub
          topologyKey: "failure-domain.beta.kubernetes.io/zone"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-stub-config
  #namespace: stub
spec:
  template:
    spec:
      containers:
      - name: deploy-stub-config
        image: curlimages/curl:latest
        command: ["curl", "-T", "stub-config.json", "http://stub:8555"]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: Service
metadata:
  name: stub-service
  #namespace: stub
spec:
  selector:
    app: stub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8880
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: stub-ingress
  #namespace: stub
spec:
  backend:
    serviceName: stub
    servicePort: 80
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: stub
  #namespace: stub
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: stub
  minReplicas: 3
  maxReplicas: 30
  targetCPUUtilizationPercentage: 50

