#apiVersion: v1
#kind: Namespace
#metadata:
#name: stub
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stub-deployment
  #namespace: stub
  labels:
    app: stub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stub
  template:
    metadata:
      labels:
        app: stub
    spec:
      containers:
      - name: hoverfly
        image: docker.io/spectolabs/hoverfly
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
        command: ["/bin/hoverfly"]
        args: ["-listen-on-host=0.0.0.0", "-webserver", "-import", "https://raw.githubusercontent.com/monch1962/kube-stub/master/stub-configs/stub-config.json"]
        ports:
          - containerPort: 8500
            name: access
          - containerPort: 8888
            name: admin
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: /api/health
            port: 8888
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /api/health
            port: 8888
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - stub
          topologyKey: "failure-domain.beta.kubernetes.io/zone"
---
apiVersion: v1
kind: Service
metadata:
  name: stub-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
  #namespace: stub
spec:
  selector:
    app: stub
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      name: admin
    - protocol: TCP
      port: 80
      targetPort: 8500
      name: stub
  type: LoadBalancer
---
#apiVersion: batch/v1
#kind: Job
#metadata:
#  name: deploy-stub-config
#spec:
#  template:
#    spec:
#      containers:
#      - name: deploy-stub-config
#        image: buildpack-deps:curl
#        args:
#        - /bin/sh
#        - -ec
#        - curl -T stub-config.json http://stub-service:8500/api/v2/simulation
#      restartPolicy: Never
#  backoffLimit: 4
---
#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: stub-ingress
#spec:
#  backend:
#    serviceName: stub-service
#    servicePort: 80
#---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: stub
  #namespace: stub
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: stub
  minReplicas: 1
  maxReplicas: 30
  targetCPUUtilizationPercentage: 50

