#apiVersion: v1
#kind: Namespace
#metadata:
#name: stub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stub-deployment
  #namespace: stub
  labels:
    app: stub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stub
  template:
    metadata:
      labels:
        app: stub
  containers:
    - name: stubby
      image: spectolabs/hoverfly:latest
      ports:
        - containerPort: 80
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - stub
          topologyKey: "failure-domain.beta.kubernetes.io/zone"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-stub-config
  #namespace: stub
spec:
  template:
    spec:
      containers:
      - name: deploy-stub-config
        image: curlimages/curl:latest
        command: ["curl", "-T", "stub-config.json", "http://stub:8500"]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: Service
metadata:
  name: stub-service
  #namespace: stub
spec:
  selector:
    app: stub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: stub-ingress
  #namespace: stub
spec:
  backend:
    serviceName: stub
    servicePort: 80
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: stub
  #namespace: stub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stub
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Pods
      pods:
        metric:
          name: packets-per-second
        target:
          type: AverageValue
          averageValue: 1k
    - type: Object
      object:
        metric:
          name: requests-per-second
        describedObject:
          apiVersion: networking.k8s.io/v1beta1
          kind: Ingress
          name: stub-route
        target:
          type: Value
          value: 10k
status:
  observedGeneration: 1
  lastScaleTime: <some-time>
  currentReplicas: 2
  desiredReplicas: 2
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1beta1
        kind: Ingress
        name: stub-route
      current:
        value: 10k
